### ISSUE TITLE
contract / 2 : payout milestone RoundImplementation contract changes

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#1094]
### Description

This ticket tracks all the changes which would need to be done on the RoundFactory to build the payout milestone

**New Changes**
- [x] New constant variable: VERSION set to 0.2.0
- [x] New variable: amount uint ( this is round pot ) 
- [x] New Event:  `AmountUpdated(uint256 newAmount, uint256 oldAmount)`
- [x] New Event : `PayFeeAndEscrowFundsToPayoutContract(uint256 amount, uint feeAmount);`
- [x] New Modifier: roundHasEnded // to know if round has ended
- [x] New Function: updateAmount (invoked before Round has ended and by operator)
    - [x] cannot be set to amount lower the set amount  
    - [x] invoked before roundHasEnded and by round opeartor
    - [x] emit AmountUpdated
- [x] New Function: isReadyForPayout 
   - [x] invoked after roundHasEnded and by round operator
   - [x] ensure contract has enough funds
   - [x] deduct protocol fee
   - [x] transfer funds to payout contract
   - [x] emit PayFeeAndEscrowFundsToPayoutContract
- [x] Remove updateDistribution (this will be written in payout contract)
- [ ] Update tests to ensure all changes are unit tested

**Refactor / Making Improvements Changes**
- [x] Update variable type:  token address (to record native + ERC20 token)
- [x] Remove redundant event being sent on init
- [x] Reduce error message string size
- [x] Updating initialize to use struct instead of variable (A function cannot have > 11 args and we have hit that limit)
   - [x] New struct: InitAddress  (votingStrategy, payoutStrategy, withdrawFundsAddress)
   - [x] New struct: InitRoundTime  (all round related timings)
   - [x] New struct: InitMetaPtr  (all round related MetaPtr)
   - [x] New struct: InitRoles  (all round related Roles)
   - [x] Update  `initialize` to use the above structs

**Comment by thelostone-mc** [comment]
- check if amount can be reduced / if we should add restrictions

**Comment by thelostone-mc** [comment]
- should payout -> be  renamed to isReadyForPayout and that just transfers funds
- this means user would have to do another transaction to actually do payout (implemented on the payout contract)

**Comment by thelostone-mc** [comment]
- Drop bonusProtocolFeePercentage
- Add roundFeePercentage which allows roundOperator to take a cut of the contract
