### ISSUE TITLE
contract / 5 : payout milestone MerklePayoutStrategyImplementation contract changes

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/grants-round#1110]
### Description

This ticket tracks all the changes which would need to be done on the MerklePayoutStrategy to build the payout milestone

**MerklePayoutStrategyImplementation**

Refer https://github.com/gitcoinco/merkle_payouts/blob/main/contracts/MerklePayout.sol as reference

- [x] New constant variable: VERSION set to 0.2.0
- [x] [New struct Claim](https://github.com/gitcoinco/merkle_payouts/blob/main/contracts/MerklePayout.sol#L74)
- [x] Remove MetaPtr public distributionMetaPtr; (this is already provided at the interface)
- [x] Update updateDistribution to ensure only isRoundOperator can invoke the function
- [x] New function [hasClaimed](https://github.com/gitcoinco/merkle_payouts/blob/main/contracts/MerklePayout.sol#L114) which checks if individual claim/payout has already been made
- [x] New function: claim which accepts an array of claims and pays the claimed if it's not already been made
   - [x] Emit event FundsClaimed for every payout 
   - [x] Ensure there is function to update who has [claimed](https://github.com/gitcoinco/merkle_payouts/blob/main/contracts/MerklePayout.sol#L101)
- [x] add script to deploy the implementation contract

**Comment by bhargavaparoksham** [comment]
@thelostone-mc is updating distribution & merkle root allowed once a partial distribution is made?

cc: @hmrtn @nfrgosselin

**Comment by thelostone-mc** [comment]
@bhargavaparoksham That shouldn't be allowed
