### ISSUE TITLE
Refactor: Context API

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#329]
**Overview**
We are switching from RTK Query to React Context for easier testability and are tracking the places where that needs to happen. Please check these off as you finish them. Original spike ticket: #298

**Checklist**

- [x] Convert useCreateProgramMutation RTK Query hook to use React Context instead. - in #398 
- [x] Convert useListRoundsQuery RTK Query hook to use React Context instead - in #105
- [x] Convert useCreateRoundMutation RTK Query hook to use React Context instead - in #399
- [x] Convert useListGrantApplicationsQuery RTK Query hook to use React Context instead - in #290 
- [x] Convert useUpdateGrantApplicationMutation RTK Query hook to use React Context instead - can do in #401 
- [x] Convert useBulkUpdateGrantApplicationsMutation RTK Query hook to use React Context instead - can do in #400
